package TgBot.botstate;

public enum BotState {
    TRELLO_ACCOUNT_AUTHORIZATION, START, TRELLO_ACCOUNT, ASK_ORGANIZATION_SUBSCRIBTION, SHOW_BOARDS,
    SHOW_SUBSCRIBED_BOARDS, SHOW_ORGANIZATIONS, SHOW_SUBSCRIBED_ORGANIZATIONS, SHOW_HELP_MENU, AFK, SHOW_COMMANDS,
    ASK_BOARDS_SUBSCRIBTION, DELETE_ORGANIZATION, DELETE_BOARD, SUBSCRIBE_TO_BOARD, SUBSCRIBE_TO_ORGANIZATION,
    DELETE_BOARD_INFORMATION, DELETE_ORGANIZATION_INFORMATION;
}